In [33]:
import pandas as pd
import geopandas as gpd

In [34]:
traffic = pd.read_parquet("/share/ju/sidewalk_utils/data/nyc/processed/nexar2020_tuesthurs_subset_traffic.parquet")

In [35]:
traffic['num_pedestrians'].describe()

count    6.077394e+06
mean     5.185099e-01
std      1.194864e+00
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.000000e+00
max      3.100000e+01
Name: num_pedestrians, dtype: float64

In [36]:
traffic

,image_name,task_id,is_pedestrian,num_pedestrians
0,fod_00D28E6B-30A9-4ED9-8408-9305765A2917,1,True,2
1,fod_00D2904E-3CB4-4B23-AE93-E2E34C9E17A3,1,True,3
2,fod_00D29E32-71BE-4AD2-8DBF-C2F582C7D7E7,1,True,1
3,fod_00D2A871-9AF0-4521-99B1-DC57705E2F34,1,True,3
4,fod_00D2AC94-B634-4E7F-B1EF-626C036DFBDA,1,True,1
...,...,...,...,...
6077389,fod_FF367E5F-357C-4A19-9553-008C11AD18C5.jpg,491,False,0
6077390,fod_FEEE0818-92E3-49CE-82CC-822EBFD20562.jpg,491,False,0
6077391,fod_FEB9BB8A-162C-4D62-8CB2-C85D9F0C5B70.jpg,491,False,0
6077392,fod_FE7560CE-F1FC-41AD-A1C8-87518BF05E84.jpg,491,False,0
6077393,fod_FE77A608-5B6E-45BE-9AD6-55D6D49DB73B.jpg,491,False,0

In [37]:
# strip .jpg from filenames
traffic['image_name'] = traffic['image_name'].str.replace('.jpg', '', regex=False)

In [38]:
traffic

,image_name,task_id,is_pedestrian,num_pedestrians
0,fod_00D28E6B-30A9-4ED9-8408-9305765A2917,1,True,2
1,fod_00D2904E-3CB4-4B23-AE93-E2E34C9E17A3,1,True,3
2,fod_00D29E32-71BE-4AD2-8DBF-C2F582C7D7E7,1,True,1
3,fod_00D2A871-9AF0-4521-99B1-DC57705E2F34,1,True,3
4,fod_00D2AC94-B634-4E7F-B1EF-626C036DFBDA,1,True,1
...,...,...,...,...
6077389,fod_FF367E5F-357C-4A19-9553-008C11AD18C5,491,False,0
6077390,fod_FEEE0818-92E3-49CE-82CC-822EBFD20562,491,False,0
6077391,fod_FEB9BB8A-162C-4D62-8CB2-C85D9F0C5B70,491,False,0
6077392,fod_FE7560CE-F1FC-41AD-A1C8-87518BF05E84,491,False,0
6077393,fod_FE77A608-5B6E-45BE-9AD6-55D6D49DB73B,491,False,0

In [39]:
md = gpd.read_parquet("/share/ju/sidewalk_utils/data/raw_export/nexar2020_geo_6077397_20250329_000919.parquet")

In [40]:
traffic = traffic.merge(md, left_on='image_name', right_on='frame_id', how='left')

In [41]:
traffic.isna().sum()

image_name         0
task_id            0
is_pedestrian      0
num_pedestrians    0
image_ref          0
timestamp          0
lat                0
lng                0
frame_id           0
date               0
geometry           0
dtype: int64